starting amount: 100
block-based: true
slots:
    '3':
        yaw: -94.49998
        sign2:
            z: -1606
            y: 43
            x: -1289
        sign1:
            z: -1607
            y: 43
            x: -1289
        pitch: -19.949957
        z: -1606.0445319131063
        y: 41.0
        world: world
        x: -1290.3730479809453
    '2':
        yaw: -92.24997
        sign2:
            z: -1609
            y: 43
            x: -1289
        sign1:
            z: -1610
            y: 43
            x: -1289
        pitch: 5.1000404
        z: -1608.9200962700484
        y: 41.0
        world: world
        x: -1290.116235729288
    '1':
        yaw: -105.60021
        sign2:
            z: -1612
            y: 43
            x: -1289
        sign1:
            z: -1613
            y: 43
            x: -1289
        pitch: -26.8499
        z: -1612.125
        y: 41.0
        world: world
        x: -1289.65625
        sign0:
            z: -1613
            y: 43
            x: -1289
    '5':
        yaw: -99.00001
        sign2:
            z: -1600
            y: 43
            x: -1289
        sign1:
            z: -1601
            y: 43
            x: -1289
        pitch: -22.499971
        z: -1599.895363916604
        y: 41.0
        world: world
        x: -1290.3513073883516
    '4':
        yaw: -106.049965
        sign2:
            z: -1603
            y: 43
            x: -1289
        sign1:
            z: -1604
            y: 43
            x: -1289
        pitch: -19.949957
        z: -1602.8795338758584
        y: 41.0
        world: world
        x: -1290.410708236659
minBet: 1
console-based: true
